// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJ32Q5Wlo5tiHtmyb7riPAcbz-ZVqvLmU',
    appId: '1:23408367101:web:2cc70fc1aa89bd6c557594',
    messagingSenderId: '23408367101',
    projectId: 'nilora-mood-journal-app',
    authDomain: 'nilora-mood-journal-app.firebaseapp.com',
    storageBucket: 'nilora-mood-journal-app.firebasestorage.app',
    measurementId: 'G-5YEZBXNQEW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB81tmjAdYH8Y-9HG5Ah-JxPamwtZpOzwA',
    appId: '1:23408367101:android:5bc7a9d90b0d6ec9557594',
    messagingSenderId: '23408367101',
    projectId: 'nilora-mood-journal-app',
    storageBucket: 'nilora-mood-journal-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvGqmeVVxqCXghrll_wlcuBEmFxO9Qm_M',
    appId: '1:23408367101:ios:836aa34367e086e5557594',
    messagingSenderId: '23408367101',
    projectId: 'nilora-mood-journal-app',
    storageBucket: 'nilora-mood-journal-app.firebasestorage.app',
    iosBundleId: 'com.example.moodJournalApp',
  );
}
